# 数据库配置信息
spring:
  profiles:
    active: dev #https
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    validation-query: SELECT 1
    test-on-borrow: true
  redis:
      database: 0
      host: localhost
      #password: # Login password of the redis server.
      port: 6379
      timeout: 0
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接数
        max-wait: -1 #最大等待时间
        min-idle: 0 #初始化连接数
  data:
    mongodb:
      database: test # Database name.
      host: localhost # Mongo server host.
      port: 27017 # Mongo server port.

server:
  port: 8090

logging:
  level:
    ROOT: ERROR
    cn.zhangxd.server: DEBUG
    org.apache.coyote.http11.InternalNioInputBuffer: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: DEBUG
